/* Degree & Radian Conversion Constants */

#define PI 3.1415927f
#define HALF_PI PI/2.0f

#define DEGREES_TO_RADIANS PI/180.0f
#define RADIANS_TO_DEGREES 180.0f/PI

/* Viewport Size Constants */
//#define WIDTH 768
//#define HEIGHT 768
#define WIDTH 256
#define HEIGHT 256

#define LIGHT_SOURCE_MAXIMUM 10
#define RAYS_PER_PIXEL_MAXIMUM 12

// PUT RAYS IN PSOTIONS THAT MAKE THEM SIMILAR

// FOR INSTANCE ALL REFLECTIONS ADJANCENT TO EACH OTHER, ALL REFRACTIONS ADJACENT TO EACH OTHER, ALL LIGHTS AJDACENT